# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_html5video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerhtml5video',
            name='alignment',
            field=models.CharField(blank=True, choices=[(b'left', 'Left'), (b'right', 'Right'), (b'center', 'center')], max_length=10, null=True, verbose_name='video alignment'),
        ),
        migrations.AddField(
            model_name='filerhtml5video',
            name='video_url',
            field=models.CharField(blank=True, help_text=b'Link to the youtube or vimeo page. Example: https://www.youtube.com/watch?v=12345678', max_length=255, verbose_name='Video URL'),
        ),
    ]
